version: '3.8'
services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://reeloom:reeloom123@db:5432/reeloom
      NODE_ENV: development
      LOG_FORMAT: json
      LOG_LEVEL: info
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: nodemon --watch src src/server.ts
    depends_on:
      - db
